name: rlaehgus
services:
  blog:
    build: ./docker/httpd
    expose:
      - 80
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          #pids: 1
        reservations:
          cpus: '0.25'
          memory: 20M
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80

  load_balancer:
    image: nginxproxy/nginx-proxy
    container_name: blog-lb
    ports:
      - 8949:80
    depends_on:
      - blog
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
